### ISSUE TITLE
Question for Beacons

### ISSUE THREAD

**Issue by ucola** [nesimtunc/stepping#3]
Hi Nesim

We review your project and looks nice! We have a use case and want to contact you... But your mail reply us "550 No such address", how can we contact you?

**Comment by nesimtunc** [comment]
Hi @ucola 

Thanks for reaching out, yeah I had to paused my email address for a while due to spams. Sorry for the inconvenience.  Please send me an email to this  temporary email address, so, we can contact from there:

counts_blithe.0f@icloud.com

Thanks!
